services:
  - type: web
    name: baadh-mitra-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.seed && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    region: singapore
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: ALLOWED_ORIGINS
        value: "http://localhost:5173"
